CREATE TABLE "Audit" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "ActionType" integer NOT NULL,
    "ObjectIdentifier" text NULL,
    "ObjectType" text NULL,
    "ObjectMetadata" text NULL,
    "SubjectType" integer NOT NULL,
    "SubjectIdentifier" text NULL,
    "Host" text NULL,
    "RemoteIp" text NULL,
    "ResourceName" text NULL,
    "UserAgent" text NULL,
    "TraceIdentifier" text NULL,
    "AppVersion" text NULL,
    "Created" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_Audit" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20201012130535_AddAudit', '3.1.5');

