CREATE TABLE "UserImage" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "_CreatedDate" timestamp with time zone NULL,
    "_ModifiedDate" timestamp with time zone NULL,
    "BlobImage" bytea NOT NULL,
    "FileName" character varying(250) NOT NULL,
    "UserId" text NOT NULL,
    CONSTRAINT "PK_UserImage" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserImage_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_UserImage_UserId" ON "UserImage" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200811085508_AddUserImageTable', '3.1.5');

