CREATE TABLE "UserAttributes" (
    "Id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" text NOT NULL,
    "Value" text NULL,
    "UserId" text NULL,
    "_CreatedDate" timestamp with time zone NULL,
    "_ModifiedDate" timestamp with time zone NULL,
    CONSTRAINT "PK_UserAttributes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserAttributes_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserAttributes_Key" ON "UserAttributes" ("Key");

CREATE INDEX "IX_UserAttributes_UserId" ON "UserAttributes" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200831195154_AddUserAttributes', '3.1.5');

